{
 "title": "Pizza Dashboard",
 "description": "Dashboard showing key metrics sent relating to JWT Pizza and it's services.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "DATA_SOURCE",
    "label": "Specify dynamic filters on all data fields."
   }
  ]
 },
 "panels": [
  {
   "title": "Unique Active Users",
   "type": "timeseries",
   "description": "Shows unique user names accessing the system. Options for hourly, daily, and weekly totals.",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 0 },
   "targets": [
    { "expr": "max(users_active_hour)", "legendFormat": "Hourly" }
   ]
  },
  {
   "title": "Authentication Attempts",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    { "expr": "rate(auth_successful[5m])", "legendFormat": "Successful" },
    { "expr": "rate(auth_failed[5m])", "legendFormat": "Failure" }
   ]
  },
  {
   "title": "HTTP Requests by Method",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    { "expr": "rate(http_total_requests[1m])", "legendFormat": "Total" },
    { "expr": "rate(http_requests_get[1m])", "legendFormat": "Get" },
    { "expr": "rate(http_requests_post[1m])", "legendFormat": "Post" },
    { "expr": "rate(http_requests_delete[1m])", "legendFormat": "Delete" },
    { "expr": "rate(http_requests_put[1m])", "legendFormat": "Put" }
   ]
  },
  {
   "title": "Total Revenue",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sales_revenue", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "System Usage Values",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 4, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sys_cpu", "legendFormat": "CPU" },
    { "expr": "sys_mem", "legendFormat": "Memory" }
   ]
  },
  {
   "title": "HTTP Results",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 11, "x": 13, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    { "expr": "rate(http_results_success[1m])", "legendFormat": "Successful" },
    { "expr": "rate(http_results_error[1m])", "legendFormat": "Errors" }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "max(lat_factory)", "legendFormat": "Factory (HQ)" },
    { "expr": "lat_service - lat_factory", "legendFormat": "Service (blame)" },
    { "expr": "lat_service", "legendFormat": "Total " }
   ]
  },
  {
   "title": "Orders Placed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "rate(sales_qty[$__rate_interval])",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}