{
 "title": "Pizza Dashboard",
 "description": "Dashboard showing key metrics sent relating to JWT Pizza and it's services.",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "METRICS_SOURCE", "label": "Metrics" },
   { "name": "LOGS_SOURCE", "label": "Logs" }
  ]
 },
 "panels": [
  {
   "title": "Unique Active Users",
   "type": "timeseries",
   "description": "Shows unique user names accessing the system. Options for hourly, daily, and weekly totals.",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 0 },
   "targets": [
    { "expr": "max(users_active_hour)", "legendFormat": "Hourly" }
   ]
  },
  {
   "title": "Authentication Attempts",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    { "expr": "rate(auth_successful[5m])", "legendFormat": "Successful" },
    { "expr": "rate(auth_failed[5m])", "legendFormat": "Failure" }
   ]
  },
  {
   "title": "HTTP Requests by Method",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    { "expr": "rate(http_total_requests[1m])", "legendFormat": "Total" },
    { "expr": "rate(http_requests_get[1m])", "legendFormat": "Get" },
    { "expr": "rate(http_requests_post[1m])", "legendFormat": "Post" },
    { "expr": "rate(http_requests_delete[1m])", "legendFormat": "Delete" },
    { "expr": "rate(http_requests_put[1m])", "legendFormat": "Put" }
   ]
  },
  {
   "title": "Total Revenue",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sales_revenue", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "System Usage Values",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 4, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sys_cpu", "legendFormat": "CPU" },
    { "expr": "sys_mem", "legendFormat": "Memory" }
   ]
  },
  {
   "title": "HTTP Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 11, "x": 13, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    { "expr": "rate(http_results_success[1m])", "legendFormat": "Successful" },
    { "expr": "rate(http_results_error[1m])", "legendFormat": "Errors" }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "max(lat_factory)", "legendFormat": "Factory (HQ)" },
    { "expr": "lat_service - lat_factory", "legendFormat": "Service (blame)" },
    { "expr": "lat_service", "legendFormat": "Total " }
   ]
  },
  {
   "title": "Orders Placed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "rate(sales_qty[$__rate_interval])",
     "legendFormat": "Successes"
    },
    {
     "expr": "rate(sales_failed_requests[$__rate_interval])",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "All Logs Sample",
   "type": "logs",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "{component=~\"jwt-pizza-service.*\"} | json",
     "maxLines": 30
    }
   ]
  },
  {
   "title": "Log Volume",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 22 },
   "targets": [
    {
     "expr": "count_over_time({component=~\"jwt-pizza-service.*\"}[$__auto])",
     "legendFormat": "{{level}}"
    }
   ]
  },
  { "title": "List of Annotations", "type": "annolist", "gridPos": { "h": 16, "w": 8, "x": 0, "y": 30 } },
  {
   "title": "HTTP Warn Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 30 },
   "targets": [
    {
     "expr": "{component=~\"jwt-pizza-service.*\"} | json | type = `http` | level != `info`",
     "maxLines": 30
    }
   ]
  },
  {
   "title": "HTTP Info Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 38 },
   "targets": [
    {
     "expr": "{component=~\"jwt-pizza-service.*\"} | json | type = `http` | level = `info`",
     "maxLines": 30
    }
   ]
  },
  {
   "title": "Unhandled Error Log Volume",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "sum by (message) (count_over_time({component=~\"jwt-pizza-service.*\", type=\"unhandledError\"} | json | line_format `{{.message}}` [$__auto]))",
     "legendFormat": "{{message}}"
    }
   ]
  },
  {
   "title": "Detailed DB Query Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 46 },
   "targets": [
    {
     "expr": "{type=`db`} | logfmt | drop __error__, __error_details__",
     "maxLines": 30
    }
   ]
  },
  {
   "title": "Detailed Factory Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 46 },
   "targets": [
    {
     "expr": "{type=`factory`} | json | logfmt | drop __error__, __error_details__",
     "maxLines": 10
    }
   ]
  }
 ]
}